all:
	g++ OpenGL_103.cpp ../common/GLShader.cpp -lGL -lGLEW -lglfw -lGLU -ldl -o a.out
test:
	g++ test2.cpp ../common/GLShader.cpp -I ../common/GLShader.h -lGL -lGLEW -lglfw -lGLU -ldl -o test.o
test2:
	g++ test2.cpp ../common/GLShader.cpp -I../common/ -lGL -lGLEW -lglfw -lGLU -ldl -o test.o

raj_all:
	g++ OpenGL_103.cpp ../common/GLShader.cpp -lGL -lGLEW -lglfw -lGLU -lglut -o a.out
raj_test:
	g++ test2.cpp ../common/GLShader.cpp -I ../common/GLShader.h -lGL -lGLEW -lglfw -lGLU -lglut -o test.o
raj_test2:
	g++ test2.cpp ../common/GLShader.cpp -I../common/ -lGL -lGLEW -lglfw -lGLU -lglut -o test.o